#! / usr/bin/env python3.

print("Tip Calculator")
print()


cost_of_meal = float(input("Cost of meal :\t"))
print()

print("15%")
tip_amount = round(cost_of_meal * .15, 2)
total_amount = round(cost_of_meal + tip_amount, 2)
print("Tip amount: ", tip_amount)
print("Total amount: ", total_amount)
print()

print("20%")
tip_amount = round(cost_of_meal * .20, 2)
total_amount = round(cost_of_meal + tip_amount, 2)
print("Tip amount: ", tip_amount)
print("Total amount: ", total_amount)
print()

print("25%")
tip_amount = round(cost_of_meal * .25, 2)
total_amount = round(cost_of_meal + tip_amount, 2)
print("Tip amount: ", tip_amount)
print("Total amount: ", total_amount)
print()